{
    "az_resource_group": "${az_resource_group}",
    "az_vnet": "${vnet_name}",
    "az_subnet": "${subnet_name}",
    "nsg_id": "${nsg_id}",
    "allow_ips": ${allow_ips},
    "linux_bastion": ${linux_bastion},
    "az_vm_name_linux_bastion": "${linux_bastion_name}",
    "url_linux_hana_studio": "${url_linux_hana_studio}",
    "url_linux_sapcar": "${url_linux_sapcar}",
    "az_user_linux_bastion": "${vm_user_linux_bastion}",
    "vm_size_linux_bastion": "${vm_size_linux_bastion}",
    "private_ip_address_linux_bastion": "${private_ip_address_linux_bastion}",
    "az_public_key": "${sshkey_path_public}",
    "ssh_private_key_file": "${sshkey_path_private}",
    "create_windows_bastion": ${windows_bastion},
    "pw_bastion_windows": "${pw_bastion_windows}",
    "bastion_username_windows": "${bastion_username_windows}",
    "az_domain_name": "${az_domain_name}",
    "private_ip_address_windows_bastion": "${private_ip_address_windows_bastion}",
    "url_sapcar_windows": "${url_sapcar_windows}",
    "url_hana_studio_windows": "${url_hana_studio_windows}",
    "vm_name_win_bastion": "${vm_name_win_bastion}"
}